command-snapshot.json, messages/agent.create.md, messages/agent.create.spec.md, src/commands/agent/create.ts, src/commands/agent/create/spec.ts
Adds some mocking around agent creation.
=> fix: some mocking around agent creation

README.md, package.json, yarn.lock
=> Add agents library

package.json, yarn.lock
=> Bump agents library

src/commands/agent/create.ts, src/commands/agent/generate/spec.ts, src/commands/agent/test/cancel.ts, src/commands/agent/test/run.ts
at planning/discussions, until the APIs are GA, the commands must be BETA
=> chore: make commands beta

package.json, src/commands/agent/generate/spec.ts, yarn.lock
What does this PR do?
updates type based on API
What issues does this PR fix or reference?
=> chore: update AgentJobSpecCreateConfig type per API

package.json, src/commands/agent/generate/spec.ts, yarn.lock
updates agent spec file schema
updates agent lib with correct enums
=> fix: update agent lib, update enums, update spec file schema

command-snapshot.json, messages/agent.generate.definition.md, messages/agent.generate.testset.md, package.json, src/commands/agent/generate/definition.ts, src/commands/agent/generate/spec.ts, src/commands/agent/generate/testset.ts, src/inquirer-theme.ts, test/commands/agent/generate/testset.test.ts, yarn.lock
- Adds `sf agent generate testset` to generate `AiEvaluationTestSet` metadata
- Adds `sf agent generate definition` to generate `AiEvaluationDefinition` metadata
@W-17372711@
@W-17237046@
=> Generate ai tests

messages/agent.create.md, messages/agent.generate.agent-spec.md
Polishes messages for "agent create" and "agent generate agent-spec"
@W-17684955@
=> W-17684955: round 2 of edit of --help for agent create/generate spec commands

command-snapshot.json, messages/agent.generate.template.md, schemas/agent-generate-template.json, src/commands/agent/generate/template.ts
bare bones command implementation of `agent generate template`
@W-17753069@
=> W-17753069 - feat: add agent generate template command

messages/agent.create.md, messages/agent.generate.agent-spec.md
Edit help for agent create commands
@W-17684955@
=> W-17684955:  small tweaks to "agent create" and "agent generate agent-spec"

package.json, src/handleTestResults.ts, test/handleTestResults.test.ts, yarn.lock
Adds human readable formatter so that we can remove it from the agents library (https://github.com/forcedotcom/agents/pull/43)
@W-17774952@
=> fix(W-17774952): add human readable formatter

command-snapshot.json, messages/agent.generate.template.md, package.json, schemas/agent-generate-template.json, src/commands/agent/generate/template.ts, tsconfig.json, yarn.lock
Builds a BotTemplate and GenAiPlanner from a Bot
[@W-17757278@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17757278)
https://salesforce.quip.com/KyYtADNhxZmH
=> W-17757278 Generate template from Bot

src/commands/agent/generate/template.ts
Make sure the xml key/attr was missing from bot template
Testing 
[@W-17822738@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17822738)
=> W-17822738 Add xml key/attrs

messages/agent.generate.template.md
Edits help for "agent generate template"
@W-17832847@
=> W-17832847: edit help for "agent generate template"

messages/agent.generate.test-spec.md, messages/agent.test.create.md, messages/agent.test.list.md, messages/agent.test.run.md, src/commands/agent/generate/test-spec.ts, src/commands/agent/test/create.ts, src/commands/agent/test/list.ts
Edits help for "agent generate test-spec" and "agent test create"
@mdonnalley , note that I updated messages that were still in `.ts` files -- it would be cool if you could move them to the corresponding `.md` files. Thanks!
@W-17686613@
=> W-17686613: Edit help for "agent generate test-spec" and "agent test create"

command-snapshot.json, messages/agent.test.run.md, src/commands/agent/test/run.ts, test/commands/agent/test/cancel.nut.ts, test/commands/agent/test/results.nut.ts, test/commands/agent/test/resume.nut.ts, test/commands/agent/test/run.nut.ts
changes `agent run test --name` => `--api-name`
updates NUTs
updates messages
@W-17875126@
=> fix: change --name to --api-name for agent:run:test W-17875126

README.md, messages/agent.preview.md
- Updates `--agent` flag to `--name` in `sf agent preview` command
=> chore: update flags in readme for agent preview

src/commands/agent/test/run.ts
when an invalid api name is tried to be tested, throw a more helpful error 
before:
```bash
Job ID: ✘
Elapsed Time: 476ms
Error (1): Invalid AiEvalDefinitionVersion identifier
```
after
```bash
Job ID: ✘
Elapsed Time: 421ms
Error (INTERNAL_SERVER_ERROR): Invalid AiEvalDefinitionVersion identifier
Try this:
Try running "sf agent test list -o epic.4db30db40db5@orgfarm.out" to see available options
```
@W-17919275@
=> fix: suggest agent test list command when invalid name used W-17919275

messages/agent.preview.md
Changes substeps to use letters (rather than numbers) to better differentiate them.  It's not great, but it's better than before.
@W-17929554@
=> W-17929554 change substeps

messages/agent.preview.md
edit "agent preview" messages
@W-1824708@
=> W-1824708: edit messages for updated "agent preview" help

README.md, command-snapshot.json, messages/agent.create.md, messages/agent.test.create.md, src/commands/agent/create.ts, src/commands/agent/generate/agent-spec.ts, src/commands/agent/generate/test-spec.ts, src/commands/agent/test/create.ts, src/commands/agent/test/list.ts, src/commands/agent/test/results.ts, src/commands/agent/test/resume.ts, src/commands/agent/test/run.ts, test/commands/agent/generate/agent-spec.nut.ts
GA COMMANDS!!!
except 
`agent preview`
`agent test cancel` (hidden)
`agent generate template`
---
change flag names 
`sf agent create`
Change `--agent-api-name` to `--api-name`
Change `--agent-name` to `--name`
`sf agent test create`
Change `--test-api-name` to `--api-name`
@W-18394325@
@W-18394841@
=> Wr/ga W-18394325

README.md, src/commands/agent/generate/template.ts
GA template generate command
BEFORE/AFTER (warning gone)
[@W-18697110@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18697110)
=> W-18697110 GA template generate command

messages/agent.create.md
change genaiplanner to genaiplannerbundle
@W-18672965@
=> W-18672965: Update agent.create.md

messages/agent.preview.md
Edit "agent preview" help to use multi-apps
@W-18763411@
=> W-18763411: Edit "agent preview" help

package.json, yarn.lock
bumps library in plugin
@W-18727048@
=> fix: bump agents @W-18727048@

messages/agent.activate.md, messages/agent.activation.md, messages/agent.deactivate.md, messages/agent.preview.md
=> W-19176724: edit messages for "agent activate|deactivate"

command-snapshot.json, messages/shared.md, src/commands/agent/test/results.ts, src/commands/agent/test/resume.ts, src/commands/agent/test/run.ts, src/flags.ts, src/handleTestResults.ts
adds a `--verbose` option to `agent test run/results/resume` command to show the generatedData, if it exists
```bash
➜  ../../oss/plugin-agent/bin/run.js agent test run -n WeatherCheck --wait 30 
────────── Agent Test Run: WeatherCheck ──────────
✔ Starting Tests 895ms
✔ Polling for Test Results 20.21s
▸ Status: COMPLETED
▸ Completed Test Cases: 1/1
▸ Passing Test Cases: 1
▸ Failing Test Cases: 0
Job ID: 4KBed0000014cULGAY
Elapsed Time: 21.11s
Test Case #1
Utterance: What's the weather on August 22?
┌──────────────────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────┐
│ Test                 │ Result    │ Expected …
```
=> fix: add --verbose to agent test results/resume/run for generatedData @W-19345316@

README.md, package.json, src/commands/agent/generate/template.ts, test/commands/agent/generate/template.nut.ts, test/mock-projects/agent-generate-template/MOCK-XML/force-app/main/default/botTemplates/Guest_Experience_Agent_v1_Template.botTemplate-meta.xml, test/mock-projects/agent-generate-template/force-app/main/default/bots/Guest_Experience_Agent/Guest_Experience_Agent.bot-meta.xml
removes 
* agentTemplate
* AgentDslEnabled
* Main_Menu_Dialog
* botSource
from the Bot MD when generating BotTemplate MD
@W-19337177@
@W-19443706@
@W-19366681@
=> Wr/packaging updates @W-19337177@ @W-19443706@ @W-19366681@

package.json, src/commands/agent/generate/test-spec.ts, test/commands/agent/generate/test-spec.test.ts, yarn.lock
fixes xml parsing without plugins
removes instruction_following and factuality OOTB metrics
@W-19594402@
=> chore: remove deprecated OOTB metrics @W-19594402@

.github/workflows/onRelease.yml
=> chore: disable CTC temporarily
