- src/commands/agent/generate/spec.ts
Use the agents library to create the agent job spec
@W-17183674@
> fix: use agents library

- command-snapshot.json
- messages/agent.create.md
- messages/agent.generate.spec.md
- package.json
- src/commands/agent/create.ts
- src/commands/agent/generate/spec.ts
- yarn.lock
- Adds multi-stage output to `sf agent create`
- Adds `--name` flag to `sf agent create`
- Removes `--name` flag from `sf agent generate spec`
> feat: add multi-stage-output

- command-snapshot.json
- messages/shared.md
- package.json
- src/commands/agent/test/results.ts
- src/commands/agent/test/resume.ts
- src/commands/agent/test/run.ts
- src/flags.ts
- src/handleTestResults.ts
- yarn.lock
- Adds junit result formatter (depends on https://github.com/forcedotcom/agents/pull/14)
- Adds `--output-dir` flag to testing commands
@W-17237082@
> feat: support junit test formatter

- messages/agent.create.md
- messages/agent.generate.spec.md
- src/commands/agent/create.ts
Edits and adds a bit more info to the --help of "agent generate spec" and "agent create"
@W-17417430@
> fix: edit messages for agent create and agent generte spec

- command-snapshot.json
- messages/agent.create.md
- src/commands/agent/create.ts
changes `agent create --job-spec` to `--spec` to match `agent create spec` command
> fix: change from --job-spec to --spec [skip-validate-pr]

- package.json
- schemas/agent-test-results.json
- src/flags.ts
- src/handleTestResults.ts
- test/commands/agent/test/results.nut.ts
- test/mocks/einstein_ai-evaluations_runs_4KBSM000000003F4AQ_details.json
- yarn.lock
Add `tap` as an option for `--result-format`. Depends on https://github.com/forcedotcom/agents/pull/18
@W-17237081@
> feat: add TAP option

- messages/agent.test.cancel.md
- messages/agent.test.results.md
- messages/agent.test.resume.md
- messages/agent.test.run.md
- messages/shared.md
- src/commands/agent/test/resume.ts
- src/commands/agent/test/run.ts
Quick edit of the four new "agent test run|resume|results|cancel" commands
@W-17445020@
> fix: quick edit of "agent test" commands

- README.md
- package.json
- schemas/agent-test-results.json
- src/commands/agent/generate/testset.ts
- src/testStages.ts
- test/commands/agent/generate/testset.test.ts
- test/mocks/einstein_ai-evaluations_runs_4KBSM000000003F4AQ_details.json
- yarn.lock
Require inputs to all possible expectation types when generating a testset
> fix: require all expectations

- .github/workflows/onRelease.yml
- package.json
- test/mocks/connect_ai-assist_draft-agent-topics.json
- yarn.lock
bump agents lib to 0.7.1 to fix agent generate spec-v2 command.
@W-17664709@
> fix: bump agents lib to 0.7.1

- messages/agent.create-v2.md
- messages/agent.generate.spec-v2.md
Edits v2 versions of the two agent create commands
@W-17684955@
> first edit pass of the v2 versions of "agent create" and "agent generate spec"

- messages/agent.generate.agent-spec.md
- src/commands/agent/generate/agent-spec.ts
fix the prompt message for agent type
@W-17669620@
> W-17669620 - fix: update prompt text for agent type

- messages/agent.generate.test-spec.md
- src/commands/agent/generate/test-spec.ts
Change `--from-definition` to expect a file path to an existing `AiEvaluationDefinition`
It should error if the file doesn't exist or if the file doesn't end in `.aiEvaluationDefinition-meta.xml`
> feat: use file path for --from-definition

- command-snapshot.json
- src/commands/agent/generate/template.ts
Removes the target-org from the `agent generate template` command. It only needs to look at local files.
[@W-17832744@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17832744)
> W-17832744 remove target-org

- src/commands/agent/test/list.ts
changes the table column title to "API Name"
```bash
➜  sf agent list test                               
Warning: This command is currently in beta. Any aspect of this command can change without advanced notice. Don't use beta commands in your scripts.
┌───────────────────────┬────────────────────┬──────────────────────────┐
│ Name                  │ Id                 │ Created Date             │
├───────────────────────┼────────────────────┼──────────────────────────┤
│ Local_Info_Agent_Test │ 4KCed000000aTMrGAM │ 2025-02-13T22:21:43.000Z │
```
```bash
➜  sf agent list test                               
Warning: This command is currently in beta. Any aspect of this command can change without advanced notice. Don't use beta commands in your scripts. …
```
> fix: change table column title to API name, was already displaying it W-17875213

- src/commands/agent/generate/template.ts
Pulls the `role` from `BotVersion` and adds it to the generated `BotTemplate`
[@W-17906887@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17906887)
Visual QA:
> W-17906887 add role to BotTemplate

- src/commands/agent/generate/test-spec.ts
allows the users to select "no expected actions" for the test-spec
generates `"expectedActions: []"` in .yaml
@W-17891598@
> fix: allow no actions in generate test-spec W-17891598

- src/commands/agent/generate/template.ts
Reverts salesforcecli/plugin-agent#99
Metadata is not ready. We will add this back later
[@W-17906887@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17906887)
> Revert "W-17906887 add role to BotTemplate"

- README.md
- package.json
- src/commands/agent/generate/template.ts
Adds  conversationVariables to botTemplate
https://salesforce-internal.slack.com/archives/C084J2FS3JL/p1741142732861389
[@W-17964682@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-17964682)
> W-17964682 Add conversationVariables to botTemplate

- src/agentTestCache.ts
- src/commands/agent/test/resume.ts
- src/commands/agent/test/run.ts
- test/agentTestCache.test.ts
adds output directory to cache, will read and use it on resume
@W-17919149@
> fix: add output-dir to cache, use it if found W-17919149

- messages/agent.preview.md
Updates `sf agent preview --help` setup instructions.
Users needed to auth via JWT when setting up the user for `agent preview` to get the right scopes needed for SFAP APIs.
Simplify setup by just using web login and requesting scopes via env var.
No need to create certs, etc.
See linked slack thread in WI ⬇️ .
@W-18247080@
> fix(agent preview): update auth instructions W-18247080

- package.json
- src/commands/agent/create.ts
- yarn.lock
uses `generateApiName` from core now
requires: https://github.com/forcedotcom/sfdx-core/pull/1183
@W-18394863@
> fix: use generateApiName from core W-18394863

- src/commands/agent/preview.ts
Switches the `agent preview` command from `preview` to `beta`
[@W-18497184@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-18497184)
> W-18497184: Agent preview beta

- command-snapshot.json
- messages/agent.preview.md
- package.json
- src/commands/agent/preview.ts
- src/components/agent-preview-react.tsx
- yarn.lock
Adds a new flag to the `agent preview` command to enable apex debug logs during agent conversation preview. When this flag is enabled, during each agent message send/retrieve that executes apex code there will be an apex debug log file written to the provided output directory.
@W-18417013@
> feat: add agent preview debug mode - W-18417013

- src/flags.ts
- test/flags.test.ts
Excludes YAML files from`node_modules` directory as suggestions for file specs.
[@W-18506859@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002ELrgUYAT/view)
> W-18506859: exclude node_modules dir from yaml files inspection

- src/handleTestResults.ts
- test/handleTestResults.test.ts
- test/mocks/einstein_ai-evaluations_runs_4KBSM000000003F4AQ_results/5.json
- test/mocks/einstein_ai-evaluations_runs_4KBSM000000003F4AQ_results/6.json
Adds Metric Pass percentage to test results summary when the tests include metric assertions.
[@W-18507456@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002ELtfOYAT/view)
> W-18507456: add Metric Pass percentage to test results summary

- src/commands/agent/create.ts
Use correct flag name in success message's suggestion.
[@W-18551233@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Ecx62YAB/view)
> W-18551233: use correct flag name in success  message

- messages/agent.preview.md
And instead point to the Agentforce Dev Guide.
Updates --help for agent preview to point to AF Dev Guide for configuration steps. 
@W-19120076@
> W-19120076: Remove configuration steps from "agent preview" help

- src/commands/agent/preview.ts
Updates `agent preview` to have` --client-app` flag as not required, and adds a required env var, SF_DEMO_AGENT_CLIENT_APP which is the name of the connected app the agent is connected to.
[@W-19795168@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002MgnYWYAZ/view)
> W-19795168: remove --client-app flag req and SF_DEMO_AGENT_CLIENT_APP env var for DF Demo

- messages/agent.generate.authoring-bundle.md
- messages/agent.preview.md
- messages/agent.publish.authoring-bundle.md
- messages/agent.validate.authoring-bundle.md
- schemas/agent-generate-authoring__bundle.json
- src/commands/agent/generate/authoring-bundle.ts
- src/commands/agent/publish/authoring-bundle.ts
- src/commands/agent/validate/authoring-bundle.ts
- test/nuts/agent.generate.authoring-bundle.nut.ts
- Makes `--api-name` flag in `agent validate authoring-bundle` command _prompt-able_.
- Makes `--api-name` flag in `agent publish authoring-bundle` command _prompt-able_.
- Renames AfScript to Agent.
[@W-19804000@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002MlAW7YAN/view)
> fix: make api-name flag prompt-able and rename AfScript to Agent

- src/commands/agent/generate/authoring-bundle.ts
Use the api-name flag value as file and directory name when running agent generate authoring-bundle command.
[@W-19826552@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00002Mymh6YAB/view)
> W-19826552: use apiName as file and directory name
